version: "1"

capabilities:
  - contract_id: "abesh:httpserver2"
    values:
      host: "0.0.0.0"
      port: "9090"
      default_request_timeout: "5ms"
      default_content_type: "application/text"
      default_404_handler_enabled: "true"
      s500m: "500 error"
      s404m: "404 error"
      s403m: "403 error"
      s405m: "405 error"
      s408m: "408 request timeout"
      s499m: "499 request cancelled"
  - contract_id: "abesh:ex_echo"
    values:
      key1: "test1"
      key2: "test2"

triggers:
  - trigger: "abesh:httpserver2"
    trigger_values:
      method: "GET"
      path: "/echo/:name"
    service: "abesh:ex_echo"

start:
  - "abesh:httpserver2"
