version: "1"

capabilities:
  - contract_id: "abesh:httpserver2"
    values:
      host: "0.0.0.0"
      port: "9090"
      default_request_timeout: "5ms"

  - contract_id: "abesh:ex_echo"
    values:
      key1: "test1"
      key2: "test2"

triggers:
  - trigger: "abesh:httpserver2"
    trigger_values:
      method: "GET,POST"
      path: "/echo/:name"
    service: "abesh:ex_echo"

start:
  - "abesh:httpserver2"
